# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-28 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contables', '0002_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='montoDebe',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='montoHaber',
            field=models.FloatField(default=0.0),
        ),
    ]
