# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-29 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contables', '0003_auto_20171128_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='totalCuenta',
            field=models.FloatField(default=0.0),
        ),
    ]
