# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-29 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contables', '0005_cuentabalancegeneral'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticaEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('cantidad', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Politica de la Empresa',
                'verbose_name_plural': 'Politicas de la Empresa',
            },
        ),
    ]
