# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-29 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contables', '0006_politicaempresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
