# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-03 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contables', '0008_auto_20171129_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='cuentamayor',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='rubro',
            name='fecha',
        ),
    ]
